### PR TITLE
Start

### PR DESCRIPTION
**Pull request by Arthur-Coppey**

### CODE REVIEW

**Review by TienYou-Nathan — DISMISSED** [review]
good idea

**Review by TienYou-Nathan — DISMISSED** [review]
Better now

**Review by RJSOG — COMMENTED** [review]
UI

**Review by RJSOG — APPROVED** [review]

**Review by RJSOG — APPROVED** [review]

**Review by LeoDELPON — APPROVED** [review]
mamamia

**Review by TienYou-Nathan — APPROVED** [review]
yes

**Review by RJSOG — APPROVED** [review]
nice

**Pull request merged**
